repos:
  # YAML, JSON, file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        files: ^\.github/|\.pre-commit-config\.yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude: ^schemas/|^storage/
      - id: trailing-whitespace
        exclude: ^schemas/|^storage/
      - id: check-added-large-files
        args: ["--maxkb=100"]


